// IH744/U1.AI/src/components/AdminPostsComponent.vue
<template>
  <div>
    <table class="min-w-full bg-white">
      <thead>
      <tr>
        <th class="w-16 py-2 px-4 border-b">ID</th>
        <th class="w-20 py-2 px-4 border-b">Thumbnail</th>
        <th class="py-2 px-4 border-b">Nombre</th>
        <th class="w-40 py-2 px-4 border-b">Acciones</th>
      </tr>
      </thead>
      <tbody>
      <tr v-for="post in posts" :key="post.id">
        <td class="py-2 px-4 border-b">{{ post.id }}</td>
        <td class="py-2 px-4 border-b">
          <RouterLink :to="{ name: 'post', params: { id: post.id } }">
            <img :src="post.imageUrl" alt="Thumbnail" class="h-16 w-16 object-cover">
          </RouterLink>
        </td>
        <td class="py-2 px-4 border-b">{{ post.title }}</td>
        <td class="py-2 px-4 border-b flex space-x-4 justify-end items-center py-6">

          <button class="bg-red-500 text-white p-2 rounded flex items-center justify-center" @click="() => handleRemove(post.id)">
            <font-awesome-icon icon="trash" class="w-4 h-4"/>
          </button >

          <RouterLink :to="{ name: 'adminPostsEdit', params: { id: post.id } }"  class="bg-blue-500 text-white p-2 rounded flex items-center justify-center">
            <font-awesome-icon icon="edit" class="w-4 h-4"/>
          </RouterLink>

        </td>
      </tr>
      </tbody>
    </table>
  </div>

  <ConfirmModal :isOpen="isModalOpen" @confirm="handleConfirm" @cancel="handleCancel" :context="currentContext" />
</template>



<script lang="ts">
import { defineComponent, ref } from 'vue';
import {getPosts} from "@/stores/posts";
import {deletePost} from "@/stores/posts";
import ConfirmModal from "@/components/ConfirmModal.vue";


export default defineComponent({
  components: {
    ConfirmModal
  },
  name: 'AdminPostsComponent',
  setup() {
    const posts = ref(getPosts());

    const isModalOpen = ref(false);
    const currentContext = ref(null);

    const handleRemove = (postId: string) => {
      currentContext.value = postId;
      isModalOpen.value = true;
    };
    const openModal = (context: any) => {
      currentContext.value = context;
      isModalOpen.value = true;
    };

    const handleConfirm = () => {
      deletePost(currentContext.value);
      location.reload();
      isModalOpen.value = false;
    };

    const handleCancel = (context: any) => {
      isModalOpen.value = false;
    };


    return {
      posts,
      isModalOpen,
      openModal,
      handleConfirm,
      handleCancel,
      handleRemove

    };
  }
});
</script>

// IH744/U2.AI/src/app/admin/admin-posts/admin-posts.component.ts
import {ChangeDetectorRef, Component, OnInit} from '@angular/core';
import { Router } from '@angular/router';
import {Post} from "../../core/models/post.model";
import {PostService} from "../../core/services/post.service";
import {faRefresh, faPlus, faEdit, faTrash} from "@fortawesome/free-solid-svg-icons";

@Component({
  selector: 'app-admin-posts',
  templateUrl: './admin-posts.component.html'
})
export class AdminPostsComponent implements OnInit {
  posts: Post[] = [];
  faRefresh = faRefresh;
  faPlus = faPlus;
  faEdit = faEdit;
  faTrash = faTrash;
  isModalOpen = false;
  currentContext: string | number = '';
  currentTitle: string = '';
  currentMessage: string = '';
  currentAction: (() => void) | undefined;

  constructor(private router: Router, private postService: PostService) { }

  ngOnInit(): void {
    this.posts = this.postService.getPosts();
  }

  openDeletePostModal(postId: number): void {
    this.currentTitle = 'Eliminar Post';
    this.currentMessage = '¿Deseas eliminar este post?';
    this.currentContext = postId;
    this.currentAction = () => {
      this.postService.deletePost(this.currentContext as number)
      this.posts = this.postService.getPosts()
      this.isModalOpen = false;

    };
    this.isModalOpen = true;

  }

  openResetDBModal(): void {
    this.currentTitle = 'Restablecer Base de Datos';
    this.currentMessage = '¿Estás seguro de que quieres restablecer la base de datos?';
    this.currentAction = () => {
      this.postService.resetPosts();
      this.posts = this.postService.getPosts()
      this.isModalOpen = false;
    };
    this.isModalOpen = true;

  }

  handleModalConfirm(): void {
    if (this.currentAction === undefined) return;
    this.currentAction();
  }

  handleModalCancel(): void {
    this.isModalOpen = false;
  }
}

<div class="p-8 container mx-auto">
  <h1 class="text-3xl font-bold mb-6">Área de Administración</h1>


  <div *ngIf="posts.length; else noPosts">
    <table class="min-w-full bg-white">
      <thead>
      <tr>
        <th class="w-16 py-2 px-4 border-b">ID</th>
        <th class="w-20 py-2 px-4 border-b">Thumbnail</th>
        <th class="py-2 px-4 border-b">Nombre</th>
        <th class="w-40 py-2 px-4 border-b">Acciones</th>
      </tr>
      </thead>
      <tbody>


      <tr *ngFor="let post of posts">
        <td class="py-2 px-4 border-b">{{ post.id }}</td>
        <td class="py-2 px-4 border-b">
          <a [routerLink]="['/post', post.id]" >
            <img src="{{ post.imageUrl }}" alt="Thumbnail" class="h-16 w-16 object-cover">
          </a>
        </td>
        <td class="py-2 px-4 border-b">{{ post.title }}</td>
        <td class="py-2 px-4 border-b flex space-x-4 justify-end items-center py-6">

          <button (click)="openDeletePostModal(post.id)"  class="bg-red-500 text-white p-2 rounded flex items-center justify-center">
            <fa-icon [icon]="faTrash"></fa-icon>
          </button >

          <button [routerLink]="['/admin/posts', post.id, 'edit']"  class="bg-blue-500 text-white p-2 rounded flex items-center justify-center">
            <fa-icon [icon]="faEdit"></fa-icon>
          </button>

        </td>
      </tr>


      </tbody>
    </table>
  </div>

  <ng-template #noPosts>
    <div class="text-center py-10">
      <p>No hay posts disponibles en este momento.</p>
    </div>
  </ng-template>


  <div class="flex justify-end mt-4">

    <button (click)="openResetDBModal()" class="bg-red-500 text-white px-4 py-2 rounded hover:bg-red-600">
      Restablecer Base de Datos
      <fa-icon [icon]="faRefresh"></fa-icon>
    </button>

    <button routerLink="/admin/posts/new" class="ml-2 bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600">
      Agregar
      <fa-icon [icon]="faPlus"></fa-icon>
    </button>
  </div>

  <app-confirm-modal
    [isOpen]="isModalOpen"
    [title]="currentTitle"
    [message]="currentMessage"
    (confirm)="handleModalConfirm()"
    (cancel)="handleModalCancel()">
  </app-confirm-modal>
</div>
