// IH744/U3.AI/src/app/contact/page.tsx
function PageContact() {
    return (
        <div className="max-w-xl mx-auto bg-white p-8 shadow-md rounded-md">
            <h1 className="text-2xl font-bold mb-6">Contáctanos</h1>

            <form>
                <div className="mb-4">
                    <label className="block text-gray-700 mb-2" htmlFor="name">Nombre:</label>
                    <input className="w-full px-3 py-2 border rounded" type="text" id="name" placeholder="Tu nombre" />
                </div>

                <div className="mb-4">
                    <label className="block text-gray-700 mb-2" htmlFor="email">Email:</label>
                    <input className="w-full px-3 py-2 border rounded" type="email" id="email" placeholder="tu@email.com" />
                </div>

                <div className="mb-4">
                    <label className="block text-gray-700 mb-2" htmlFor="message">Mensaje:</label>
                    <textarea className="w-full px-3 py-2 border rounded" id="message" placeholder="Tu mensaje" rows={4}></textarea>
                </div>

                <button className="px-6 py-2 bg-blue-500 text-white rounded hover:bg-blue-600">Enviar</button>
            </form>
        </div>
    );
}

export default PageContact;

// IH744/U1.A3/src/components/ContactComponent.vue
<template>
  <div class="bg-white p-8 shadow-md rounded-md">
    <h1 class="text-2xl font-bold mb-6">Contáctanos</h1>

    <form @submit.prevent="submitForm">
      <div class="mb-4">
        <label class="block text-gray-700 mb-2" for="name">Nombre:</label>
        <input class="w-full px-3 py-2 border rounded" type="text" id="name" v-model="name" placeholder="Tu nombre">
      </div>

      <div class="mb-4">
        <label class="block text-gray-700 mb-2" for="email">Email:</label>
        <input class="w-full px-3 py-2 border rounded" type="email" id="email" v-model="email" placeholder="tu@email.com">
      </div>

      <div class="mb-4">
        <label class="block text-gray-700 mb-2" for="message">Mensaje:</label>
        <textarea class="w-full px-3 py-2 border rounded" id="message" v-model="message" placeholder="Tu mensaje" rows="4"></textarea>
      </div>

      <button class="px-6 py-2 bg-blue-500 text-white rounded hover:bg-blue-600">Enviar</button>
    </form>
  </div>
</template>

<script>
export default {
  name: 'ContactComponent',
  data() {
    return {
      name: '',
      email: '',
      message: ''
    };
  },
  methods: {
    submitForm() {
      // Aquí puedes manejar el envío del formulario, como enviarlo a una API
      console.log('Formulario enviado:', {
        name: this.name,
        email: this.email,
        message: this.message
      });
      alert('Formulario enviado. ¡Gracias!');
      this.name = '';
      this.email = '';
      this.message = '';
    }
  }
}
</script>

<style scoped>
/* Si deseas agregar estilos específicos para esta página, puedes hacerlo aquí */
</style>
